# Overrides default chart name
# default to chart name if the value is empty
nameOverride: ""
fullnameOverride: ""

image:
  name: demo-app-one
  tag: 0.1.0
  pullPolicy: Never

container_ports:
- name: http
  containerPort: 80
  protocol: TCP

readinessProbe:
  httpGet:
    path: /
    port: 5000
  initialDelaySeconds: 20
  periodSeconds: 3
  failureThreshold: 5

livenessProbe:
  httpGet:
    path: /
    port: 5000
  initialDelaySeconds: 30
  periodSeconds: 3
  failureThreshold: 5

