apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "demo-app-one.fullname" . }}
  namespace: {{ .Values.namespace | default .Release.Namespace }}
  labels:
    {{- include "demo-app-one.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "demo-app-one.labels" . | nindent 6 }}
  template:
    metadata:
      labels:
         {{- include "demo-app-one.labels" . | nindent 8 }}
    spec:
      containers: 
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.name }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        {{- if.Values.container_ports }}
        ports:
          {{- toYaml .Values.container_ports | nindent 12 }}
        {{- end }}
        resources:
          {{- toYaml .Values.resources | nindent 12 }}
        volumeMounts:
        - name: "{{ include "demo-app-one.fullname" . }}-config"
          mountPath: /app/config
          readOnly: true
      volumes:
      - name: "{{- include "demo-app-one.fullname" . }}-config"
        configMap:
          name: {{ include "demo-app-one.fullname" . }}